@startuml
'https://plantuml.com/activity-diagram-beta

|Користувач|
start
if(Авторизація) then (Звичайний користувач)
    partition Меню {
        :Завантаження музичного файла;
        :Вподобання музичних файлів;
        :Додавання музичних файлів до плейлистів;
        :Пошук;
        :Підписки на інших користувачів;
    }

|Адміністратор|
else (Адміністратор)
     partition Меню_адміністратора {
        :Перегляд усіх користувачів;
        :Перегляд усіх плейлистів;
        :Перегляд усіх жанрів;
        :Перегляд усіх музичних файлів;
     }
endif
|Користувач|
:Завершення сесії;

stop

@enduml
