@startuml
'https://plantuml.com/class-diagram

UserService <|-- PlaylistService
UserService <|-- FileUploadService
SongService <|-- FileUploadService
GenreController <|-- GenreService
UserController <|-- UserService
AuthController <|-- UserService
PlaylistController <|-- PlaylistService
SongController <|-- SongService

Song <|-- User
Song <-- Playlist
Song <|-- Genre
Playlist <|-- User

class User {
    Long id
    List<Playlist> playlists
    List<Playlist> songs
    List<Playlist> comments
    String email
    String username
    String firstName
    String password
    String lastName
    String avatar
    Set<User> subscriptions
    Set<User> subscribers
    String role
}

class Playlist {
    Long id
    User user
    String name
    Set<Song> songs
    String photoFile
    String state
}

class Song {
    Long id
    User user
    Set<Playlist> playlists
    String title
    String genre
    String songFile
    String cover
    Set<User> likes
}

class Genre {
    Long id
    String name
}

class PlaylistController {
    PlaylistService playlistService

    createPlaylist()
    updatePlaylist()
    getPlaylistsByUsername()
    getPlaylistPhoto()
    deletePlaylist()
}

class GenreController {
    GenreService genreService

    createGenre()
    getAllGenres()
}

class UserController {
    UserService userService

    getAllUsers()
    getProfileByUsername()
    updateUser()
    changeSubscription()
    getAvatar()
    delete()
}

class AuthController {
    UserService userService

    login()
    register()
}

class SongController {
    SongService songService

    getAllSongsByUsername()
    getSubscriptionsSongs()
    createSong()
    saveSongToPlaylist()
    updateLikesOfSong()
    deleteSong()
}

class GenreService {
    create()
    getGenreByName()
    getGenreById()
    getAllGenres()
}

class UserService {
    FileUploadService fileUploadService
    PlaylistService playlistService

    login()
    register()
    changeSubscription()
    getUserProfileDtoByUsername()
    updateUser()
    delete ()
    getAll()
}

class PlaylistService {
    FileUploadService fileUploadService

    getAll()
    getPlaylistById()
    deletePlaylistById()
    createPlaylist()
    getPlaylistsByUsername()
}

class SongService {
    FileUploadService fileUploadService

    getAll()
    getSongsByUsername()
    createSong()
    deleteSongById()
    updateLikesOfSong()
    getSubscriptionsSongs()
    saveSongToPlaylist()
    getSongsByGenreName()
}

class FileUploadService {
    String playlistPhotos = "uploads/playlist_photos"
    String userAvatars = "uploads/avatars"
    String songCover = "uploads/covers"
    String songs = "uploads/songs"
    String fileExpansion = ".mp3"

    savePhoto()
    cropImage ()
    saveSong ()
}

@enduml