@startuml
'https://plantuml.com/component-diagram


package "Програма" {
  HTTP -- [Сервер]
  HTTP - [Клієнт]
}



database "MySql" {
  folder "Music service" {
    [DB]
  }
}


[Сервер] --> [DB]

@enduml