@startuml
'https://plantuml.com/deployment-diagram

node Програмне_забезпечення_сервера
node Програмне_забезпечення_клієнта
node Мережевий_пристрій
database База_даних

Програмне_забезпечення_сервера - База_даних
Програмне_забезпечення_сервера -- Мережевий_пристрій
Мережевий_пристрій -- Програмне_забезпечення_клієнта


@enduml