@startuml
'https://plantuml.com/sequence-diagram

autonumber

Admin -> Авторизація: Авторизація
Admin -> User: Перегляд усіх користувачів
Admin --> Музичний_файл: Перегляд усіх музичних файлів
Admin ---> Жанр: Перегляд усіх жанрів
Admin ---> Плейлист: Перегляд усіх плейлистів
Admin ---> Вихід_з_системи: Вихід з системи

@enduml