@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> Авторизація: Авторизація
User --> Музичний_файл: Завантажити музичний файл
User --> Музичний_файл: Вподобати музичний файл
User ---> Жанр: Створити жанр
User ---> Пошук: Пошук по критеріям
User ---> Плейлист: Створити плейлист
Музичний_файл ---> Плейлист: Додати музичний файл до плейлиста
User ---> User: Підписатися на користувача
User ---> Вихід_з_системи: Вихід з системи

@enduml