@startuml
'https://plantuml.com/state-diagram

'scale 350 width
[*] -> Авторизація

state Меню {
  Авторизація ---> Створення_музичних_файлів
  Авторизація --> Пошук
  Авторизація --> Створення_плейлистів
  Створення_плейлистів --> Додавання_пісень_в_плейлисти
  Створення_музичних_файлів --> Додавання_пісень_в_плейлисти
  Створення_музичних_файлів --> Вподобання_пісень
}

[*] -> [*]
Авторизація -> Завершення_сесії_користувача
Меню ---> Завершення_сесії_користувача
Завершення_сесії_користувача -> [*]
@enduml