@startuml
'https://plantuml.com/use-case-diagram

User -> (Авторизація)
(Авторизація) -> (Завантаження пісень)
(Авторизація) --> (Підписки на інших людей)
(Авторизація) ---> (Пошук інших користувачів)
(Завантаження пісень) -> (Пошук пісень по назві та по жанрах)
(Завантаження пісень) --> (Вподобання пісень)
(Завантаження пісень) --> (Додавання пісень в плейлисти)

Admin -> (Авторизація адміна)
(Авторизація адміна) -> (Перегляд усіх користувачів, пісень, жанрів)


@enduml